### ISSUE TITLE
Potential security issue in src/core/io/ImageIO.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/tungsten#1]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/core/io/ImageIO.cpp` 
Function: `lodepng_decode_memory` 
https://github.com/sagpant/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/core/io/ImageIO.cpp#L398
Code extract:

```cpp

    uint8 *dst = nullptr;
    uint32 uw, uh;
    lodepng_decode_memory(&dst, &uw, &uh, file.get(), size_t(size), LCT_RGBA, 8); <------ HERE
    if (!dst)
        return makeVoidPixels();
```

**How can I fix it?** 
Correct reference usage found in `src/thirdparty/lodepng/lodepng.cpp` at line `6103`.
https://github.com/sagpant/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/thirdparty/lodepng/lodepng.cpp#L6103
Code extract:

```cpp
                size_t insize, LodePNGColorType colortype, unsigned bitdepth)
{
  unsigned char* buffer;
  unsigned error = lodepng_decode_memory(&buffer, &w, &h, in, insize, colortype, bitdepth); <------ HERE
  if(buffer && !error)
  {
```

**Comment by siva-msft** [comment]
lgtm
