### ISSUE TITLE
Potential security issue in src/core/io/ZipReader.cpp: Unchecked return from initialization function

### ISSUE THREAD

**Issue by monocle-ai** [sagpant/tungsten#2]
<span> What is a&nbsp;</span><span><b>Conditionally Uninitialized Variable? </b></span><span> The return value of a function that is potentially used to initialize a local variable is not checked. Therefore, reading the local variable may result in undefined behavior.</span>
---

1 instance of this defect were found in the following locations:
---
**Instance 1**
File : `src/core/io/ZipReader.cpp` 
Function: `mz_zip_reader_file_stat` 
https://github.com/sagpant/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/core/io/ZipReader.cpp#L37
Code extract:

```cpp
    int count = mz_zip_reader_get_num_files(&_archive);
    for (int i = 0; i < count; ++i) {
        mz_zip_archive_file_stat stat;
        mz_zip_reader_file_stat(&_archive, i, &stat); <------ HERE

        ZipEntry entry;
```

**How can I fix it?** 
Correct reference usage found in `src/thirdparty/miniz/miniz.c` at line `3188`.
https://github.com/sagpant/tungsten/blob/88ea02044dbaf20472a8173b6752460b50c096d8/src/thirdparty/miniz/miniz.c#L3188
Code extract:

```cpp
  mz_bool status;
  mz_zip_archive_file_stat file_stat;
  MZ_FILE *pFile;
  if (!mz_zip_reader_file_stat(pZip, file_index, &file_stat)) <------ HERE
    return MZ_FALSE;
  pFile = MZ_FOPEN(pDst_filename, "wb");
```

**Comment by siva-msft** [comment]
Valid issue. All other uses `mz_zip_reader_file_stat` are checked.
